# Starship prompt (macOS)

format = """
$conda\
$directory\
$character"""

[directory]
style = "bold #DA627D"
format = "[$path ]($style)"
truncate_to_repo = false
truncation_length = 100

[conda]
ignore_base = false
style = "bold #06969A"
format = '[$environment ]($style)'

[character]
success_symbol = "[>](bold #00ff9f)"
error_symbol = "[>](bold #ff0055)"
vimcmd_symbol = "[<](bold #00ff9f)"

[git_branch]
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true
