# Minimal Starship Prompt (Linux)

format = """
$directory $conda$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold #bd93f9"
format = "[$path]($style)"
truncation_length = 5
truncation_symbol = "~/"

[directory.substitutions]
"Documents" = "DOC"
"Downloads" = "DL"

[conda]
style = "#ff79c6"
format = "[$symbol$environment]($style) "
symbol = ""
ignore_base = false

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "dim #6272a4"
format = "[$duration]($style)"

[character]
success_symbol = "[>](bold #50fa7b)"
error_symbol = "[>](bold #ff5555)"
vimcmd_symbol = "[<](bold #50fa7b)"

[line_break]
disabled = false
