# tmux config
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-kitty:RGB"

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on
set -g history-limit 50000
set -g mouse on
set -sg escape-time 10
set -g focus-events on

setw -g mode-keys vi
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Status bar
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-position bottom
set -g status-justify left

set -g status-left-length 30
set -g status-left "#[bg=#cba6f7,fg=#1e1e2e,bold]  #S #[bg=#1e1e2e,fg=#cba6f7]"

set -g status-right-length 50
set -g status-right "#[fg=#45475a]#[bg=#45475a,fg=#cdd6f4]  %Y-%m-%d #[bg=#cba6f7,fg=#1e1e2e,bold]  %H:%M "

setw -g window-status-format "#[fg=#45475a,bg=#1e1e2e]#[bg=#45475a,fg=#cdd6f4] #I:#W #[fg=#45475a,bg=#1e1e2e]"
setw -g window-status-current-format "#[fg=#f38ba8,bg=#1e1e2e]#[bg=#f38ba8,fg=#1e1e2e,bold] #I:#W #[fg=#f38ba8,bg=#1e1e2e]"

set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#cba6f7"

set -g message-style "bg=#313244,fg=#cdd6f4"
set -g message-command-style "bg=#313244,fg=#cdd6f4"

setw -g clock-mode-colour "#cba6f7"
